version: '3.8'

services:

  redis:
    image: redis:6.0.6-alpine3.12
    ports:
      - '6379:6379'
    volumes:
      - ./infra/etc/redis.dev.conf:/usr/local/etc/redis/redis.conf

  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"

  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"

  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - "4171:4171"

  mongodb:
    image: mongo:4.4.0-bionic
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongodb_volume:/data/db
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null

volumes:
  mongodb_volume:
